### ISSUE TITLE
"Unable to find snort.config"

### ISSUE THREAD

**Issue by eddybudge** [kkoziara/alpine-snort#1]
Hi! I tried to execute your script, but container logs show me this error:
`Parsing` Rules file "/data/etc/snort/snort.config"
ERROR: /data/etc/snort/snort.config(0) Unable to open rules file "/data/etc/snort/snort.config": No such file or directory.

Fatal Error, `Quitting..`
What could cause this?

**Comment by kkoziara** [comment]
The command to run the image should be `./run.sh snort -c /etc/snort/snort.config -i <eth>`. I fixed the README.
